AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  quick-velritun-api

  Quick Velritun (typing in icelandic) an api for generating typing tests, primarily to be
  used through discord. WIP

Globals:
  Function:
    Timeout: 5

Parameters:
  WordsURL:
    Type: String
    Description:
    Default: None

Resources:
  TypingTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/cmd
      Handler: typingtest
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /typingtest
            Method: POST
      Environment:
        Variables:
          TEST_WORDS_URL: !Ref WordsURL


Outputs:
  TypingTestAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/typingtest/"
  TypingTestFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt TypingTestFunction.Arn
  TypingTestFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TypingTestFunctionRole.Arn
