AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  quick-velritun-api
  
  Sample SAM Template for quick-velritun-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  TypingTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: pkg/handlers
      Handler: typingtest
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /typingtest
            Method: POST


Outputs:
  TypingTestAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/typingtest/"
  TypingTestFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt TypingTestFunction.Arn
  TypingTestFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TypingTestFunctionRole.Arn
